Repository UMCWegg/iOS_Wegg, pull requests merged in 2025-01, with the labels that each got.

#2 이슈 템플릿 설정 파일 추가
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/pr-template.md
  README.md
Labels: docs

#6 Feature/map view
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
Labels: docs, feat

#7 [style] GmarketSans 폰트 설정
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Resources/Fonts/GmarketSansTTFBold.ttf
  iOS_Wegg/iOS_Wegg/Resources/Fonts/GmarketSansTTFLight.ttf
  iOS_Wegg/iOS_Wegg/Resources/Fonts/GmarketSansTTFMedium.ttf
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
Labels: Style

#22 docs: 네이버 지도 라이브러리 추가
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
Labels: docs

#24 style: UIFont를 확장하여 커스텀 폰트 추가
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/.gitkeep
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIFont+extensions.swift
Labels: Style

#28 docs: PR 템플릿 업데이트
  .github/pull_request_template.md
Labels: docs

#17 feat: 비밀번호 찾기 화면 구현
  iOS_Wegg/iOS_Wegg/Component/TextField/Login/LoginTextField.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/EmailLoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/FindPasswordView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/FindPasswordViewController.swift
Labels: feat

#16 feat: 둘러보기 뷰 기본 UI 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Models/BrowseItem.swift
  iOS_Wegg/iOS_Wegg/Models/BrowseItem/BrowseItem.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/post1-1.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/post1-1.imageset/post1-1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/profile1.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/profile1.imageset/profile1.png
  iOS_Wegg/iOS_Wegg/Screen/Browse/ViewController/BrowseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/CollectionView/BrowseCell.swift
Labels: feat

#29 fix: Component 폴더 파일 참조 버그 해결
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
Labels: bug

#20 feat:메인 탭 바 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Home.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Home.imageset/Home.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Map.imageset/Book.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Map.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/My.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/My.imageset/My.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Search.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Search.imageset/Search.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Time.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Time.imageset/Map.png
  iOS_Wegg/iOS_Wegg/Screen/.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/My/MyPageViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Time/TimeViewController.swift
Labels: feat

#23 feat: 검색바 UI 개발
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/ViewController/SearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseView.swift
Labels: feat

#31 fix: main 브랜치 병합 충돌 해결
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Models/BrowseItem/BrowseItem.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/ViewController/SearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/ViewController/BrowseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/My/MyPageViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Time/TimeViewController.swift
Labels: bug

#32 feat: 네이버 지도 뷰 띄우기 & 커스텀 핀 마커 생성
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/.gitkeep
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/wegg_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/wegg_icon.imageset/wegg_icon.png
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapViewController.swift
Labels: feat

#42 chore: iOS 최소 지원 타겟 변경
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
Labels: chore

#47 style: Primary 색상과 Secondary 색상 변경
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Primary.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Secondary.colorset/Contents.json
Labels: Style

#33 feat: 게시물 상세뷰 UI 및 화면간 데이터 전달 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Utilities/Formatters/.gitkeep
  iOS_Wegg/iOS_Wegg/Core/Utilities/Formatters/DateFormatterUtility.swift
  iOS_Wegg/iOS_Wegg/Models/BrowseItem/BrowseItem.swift
  iOS_Wegg/iOS_Wegg/Models/PostModel/PostDetailModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/PostDetail/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/PostDetail/Emoji.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/PostDetail/Emoji.imageset/Emoji.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/post2-1.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/post2-1.imageset/post2-2.png
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/ViewController/PostDetailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/Views/PostDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/ViewController/BrowseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/CollectionView/BrowseCell.swift
Labels: feat, refactor

#34 feat: 로그인 API 구성
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/AppDelegate.swift
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Component/Button/Login/LoginButton.swift
  iOS_Wegg/iOS_Wegg/Component/Button/SignUp/SignUpToggleButton.swift
  iOS_Wegg/iOS_Wegg/Component/TextField/Login/LoginTextField.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Auth/AuthService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Auth/EmailLoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Auth/GoogleLoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Auth/GoogleService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Auth/KakaoLoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Auth/LoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/Login/Storage/UserDefaultsManager.swift
  iOS_Wegg/iOS_Wegg/Models/ResponseModel/Login/LoginRequest.swift
  iOS_Wegg/iOS_Wegg/Models/ResponseModel/Login/LoginResponse.swift
  iOS_Wegg/iOS_Wegg/Models/ResponseModel/Login/UserModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Login/TextField.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Login/BackButton.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Login/BackButton.imageset/back_button.png
  iOS_Wegg/iOS_Wegg/Resources/GoogleService-Info.plist
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/Login/View/EmailLoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/FindPasswordView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/LoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/EmailLoginViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/LoginViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/ServiceAgreementView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/ServiceAgreementViewController.swift
Labels: feat

#49 feat: 서비스 이용 동의 화면 구현
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Component/Button/SignUp/SignUpToggleButton.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/ServiceAgreementView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/ServiceAgreementViewController.swift
Labels: bug, feat

#40 feat: MapViewOverlay 제작 및 MapViewController와 상호작용
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/current_position_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/current_position_icon.imageset/Frame 52.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/map_search_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/map_search_icon.imageset/Frame 427319004.png
  iOS_Wegg/iOS_Wegg/Screen/Map/View/MapOverlayGestureDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/MapOverlayView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/ViewController/MapViewController.swift
Labels: feat

#51 refactor: 디자인 코드 수정 및 API Key 숨기기
  .gitignore
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/AppDelegate.swift
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Component/Button/Login/LoginButton.swift
  iOS_Wegg/iOS_Wegg/Component/Button/SignUp/SignUpToggleButton.swift
  iOS_Wegg/iOS_Wegg/Core/Secrets/APIKeys.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/AuthService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/EmailLoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/GoogleLoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/GoogleService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/KakaoLoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/LoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Storage/UserDefaultsManager.swift
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/Login/View/EmailLoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/FindPasswordView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/LoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetEmailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/EmailSignUpView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/ServiceAgreementView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/SignUpView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/EmailSignUpViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/ServiceAgreementViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpViewController.swift
Labels: refactor, Style

#55 feat: 전화번호 입력 화면 구현
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/SignUp/weggy!.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/SignUp/weggy!.imageset/weggy!.png
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/PhoneNumberInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberInputViewController.swift
Labels: feat

#59 feat: 이름 입력 화면 구현
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/NameInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/PhoneNumberInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/NameInputViewController.swift
Labels: feat

#72 feat: 알림 허용 화면 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Component/Label/Login/LoginLabel.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIFont+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/ResponseModel/User/UserModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Login/SubTitle.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/SignUp/alert_phone.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/SignUp/alert_phone.imageset/phone_alert.png
  iOS_Wegg/iOS_Wegg/Screen/Login/View/EmailLoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetEmailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/EmailSignUpView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/GetAlertPermissionView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/NameInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/NickNameInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/OccupationInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/PhoneNumberInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/PhoneNumberVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/ReasonInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/ServiceAgreementView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/GetAlertPermissionViewController.swift
Labels: feat, refactor, Style

#75 feat: 회원가입 완료 화면 구현
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/SignUpCompleteView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/SignUpView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpCompleteViewController.swift
Labels: feat

#79 알림 화면 UI 완성
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Home/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Home/YellowWhite.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/profileImage.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/profileImage.imageset/profileImage.png
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/AuthView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HeaderView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HomeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/SwipeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/TimerView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoListview.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/WeeklyEggView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/FollowCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/NotiCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/NotiFollowView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/NotiView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/ViewController/FollowViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/ViewController/NotiViewController.swift
Labels: feat

#80 feat: 바텀 시트 UI 제작
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/HotPlaceModel/HotPlaceSectionModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Map/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Map/captionGray.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/BottomSheet/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/BottomSheet/wegg_icon2.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/BottomSheet/wegg_icon2.imageset/Group 11.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/BottomSheet/weggy.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/BottomSheet/weggy.imageset/weggy.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_1.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_1.imageset/Unknown-5 1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_2.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_2.imageset/Unknown-4 1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_3.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_3.imageset/🪷☘️🍵🖇️🎧📁✨saturday's work_ 1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_4.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Cell/study_4.imageset/xiaohongshu 🀄️-2 1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/map_list_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/map_list_icon.imageset/nrk_list.png
  iOS_Wegg/iOS_Wegg/Screen/Map/View/CollectionView/Cell/HotPlaceCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/CollectionView/CollectionLayout/HotPlaceCollectionLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/CollectionView/Footer/SectionSeparatorFooter.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/CollectionView/Header/HotPlaceCellHeader.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/Delegate/MapOverlayGestureDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/HotPlaceSheetView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/MapOverlayView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/MapViewLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/ViewController/MapViewController.swift
Labels: docs, feat
