Repository UMCWegg/iOS_Wegg, pull requests merged in 2025-02, with the labels that each got.

#87 feat: 로그인, 회원가입 네비게이션 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/EmailLoginView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetEmailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/EmailLoginViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/LoginViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/PasswordResetEmailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/PasswordResetVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/EmailSignUpView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/View/PhoneNumberVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/EmailSignUpViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/GetAlertPermissionViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/NameInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/NickNameInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/OccupationInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/ReasonInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/ServiceAgreementViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpCompleteViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpViewController.swift
Labels: feat

#83 refacotr: ToDoList UI 완성 및 전체 Then 사용
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/AuthView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/EggProgressView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HeaderView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HomeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/SwipeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoListview.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/WeeklyEggView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
Labels: bug, refactor

#92 feat: 커스텀 검색바 제작 및 검색 결과 페이지 UI 제작
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Component/Map/MapSearchBar.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIViewController+extension.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/Map/gray1.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Search/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Search/MapSearchButton.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Search/MapSearchButton.imageset/search.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Search/searchBackButton.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Search/searchBackButton.imageset/shape.png
  iOS_Wegg/iOS_Wegg/Screen/Map/Delegate/MapOverlayGestureDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Cell/HotPlaceCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/CollectionLayout/HotPlaceCollectionLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Footer/SectionSeparatorFooter.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Header/HotPlaceCellHeader.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/HotPlaceSheetView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/MapOverlayView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/MapViewLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/View/MapSearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/ViewController/MapSearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/View/Delegate/MapOverlayGestureDelegate.swift
Labels: feat

#94 feat: 장소 상세 페이지 UI 구현
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/HotPlaceModel/HotPlaceSectionModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/gray1.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/yellow-bg.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/brown_clock.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/brown_clock.imageset/clock.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/brown_phone.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/brown_phone.imageset/shape.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/brown_web.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/brown_web.imageset/wbe.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/star.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/PlaceDetail/star.imageset/Star 1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/map_list_icon.imageset/nrk_list.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/weggy.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/weggy.imageset/weegy.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/weggy_border.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/weggy_border.imageset/weggy.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/yellow_wegg_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/yellow_wegg_icon.imageset/Group 11.png
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Header/HotPlaceCellHeader.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/HotPlaceSheetView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/MapViewLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/CollectionView/Cell/PlaceDetailImageCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/CollectionView/CollectionLayout/PlaceDetailCollectionLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/PlaceDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailViewController.swift
Labels: feat, refactor

#96 feat: 장소 상세보기 뷰 버튼 핸들러 구현
  iOS_Wegg/iOS_Wegg/Screen/Map/Delegate/Delegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/Delegate/MapOverlayGestureDelegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/PlaceDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailCollectionHandler.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailViewController.swift
Labels: feat, refactor

#98 feat: 캘린더 화면 완성
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Component/Home/HeaderView.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/home.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/home.imageset/home.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/next.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/next.imageset/next.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/previous.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/previous.imageset/previous.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/profileIcon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/profileIcon.imageset/profile.png
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/CalendarCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/CalendarView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/StudyTimeCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/StudyTimeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/ToggleButtonView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/ViewController/CalendarViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HeaderView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/WeeklyEggView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
Labels: feat, Style

#91 Style: 메인탭바 컨트롤러 스타일 변경 및 13mini 버그 수정
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Home.imageset/Home.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Map.imageset/Book.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Map.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Map.imageset/Map.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/My.imageset/My.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Search.imageset/Search.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Time.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Time.imageset/Map.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Time.imageset/Time.png
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
Labels: refactor, Style

#102 투두리스트 항목 추가 시 텍스트 기입 및 삭제
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/AuthView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/EggProgressView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/SwipeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoListview.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/WeeklyEggView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/FollowCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/NotiCell.swift
Labels: feat, refactor

#103 feat: 장소 상세보기 네비게이션 연결
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/place_back_button.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/place_back_button.imageset/Frame 427319003.png
  iOS_Wegg/iOS_Wegg/Screen/Map/Delegate/Delegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Header/HotPlaceCellHeader.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/HotPlaceSheetView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/MapOverlayView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/ViewController/MapSearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/PlaceDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailViewController.swift
Labels: feat, refactor

#105 feat: 일정 페이지 UI 제작
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/customGray.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule.imageset/add.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Schedule.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Tab/Schedule.imageset/Time.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/yellow_wegg_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/yellow_wegg_icon.imageset/Group 11.png
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleCardCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Time/TimeViewController.swift
Labels: feat

#107 feat: 공부 일정 생성 페이지 UI 제작
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIColor+extensions.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Colors/customGray2.colorset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule/CreatePlace.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule/CreatePlace.imageset/image.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddScheduleIcon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddScheduleIcon.imageset/add.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/calendar.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/calendar.imageset/calendar.png
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/AddScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/View/ScheduleCardCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/View/ScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ViewController/ScheduleViewController.swift
Labels: feat, refactor

#86 feat: APIManager 완료
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/ScheduleTargetType.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/.gitkeep
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Login/LoginRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Login/LoginResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleSearch.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/User/UserModel.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/User/UserOccupation.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/User/UserReason.swift
  iOS_Wegg/iOS_Wegg/Models/ResponseModel/.gitkeep
Labels: feat, chore

#109 feat: 사진 인증 기능
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Models/Protocol/CameraSessionManagerDelegate.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/camera_btn.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/camera_btn.imageset/camera_btn.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule.imageset/Time.png
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/Camera/CameraSessionManager.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/Camera/CameraView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/Camera/CameraViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/Camera/PreviewView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/AuthView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HomeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
Labels: feat, refactor

#111 feat: 현재 위치 기반 주변 핫플레이스 API 연결
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/HotPlacesAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/ScheduleAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/HotPlaceRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/HotPlacesResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleSearchRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleSearchResponse.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
Labels: feat, refactor

#114 feat: 게시물 등록 API 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Post/PostAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Post/PostService.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIImage+extentions.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/UploadRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/UploadResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/Camera/CameraViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
Labels: feat

#117 feat: 커스텀 캘린더 Picker UI 제작 및 바텀시트 연결
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/.gitkeep
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/AddScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleCalendar/CalendarManager.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleCalendar/View/ScheduleCalendarCollectionViewCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleCalendar/View/ScheduleCalendarView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ScheduleCalendar/ViewController/ScheduleCalendarViewController.swift
Labels: feat

#119 feat: API Response 데이터 기반 UI 업데이트
  README.md
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIImageView+extensions.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/list_brown_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/list_brown_icon.imageset/LightBrownIcon.png
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Cell/HotPlaceCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Header/HotPlaceCellHeader.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/HotPlaceSheetView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
Labels: feat, chore

#121 feat: 장소 인증 페이지 제작 및 화면 이동
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIView+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/.gitkeep
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Verification/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Verification/verification_logo.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/Verification/verification_logo.imageset/Group 130.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule.imageset/Time.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule.imageset/add.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule/AddScheduleIcon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Schedule/AddSchedule/AddScheduleIcon.imageset/add.png
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationInfoView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationViewController.swift
Labels: feat

#127 feat: todo리스트 추가 관련 api 작성 및 테스트 완료
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Todo/TodoAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Todo/TodoService.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Todo/TodoRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Todo/TodoResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoListview.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/NetworkModel/Todo/TodoRequest.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/NetworkModel/Todo/TodoResponse.swift
Labels: feat

#130 feat: 장소 검색 API 연결 및 UI 반영
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/ScheduleAPI.swift
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/NetworkModel/Schedule/ScheduleSearchRequest.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/Protocol/.gitkeep
  iOS_Wegg/iOS_Wegg/Screen/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/AddScheduleSearch/AddScheduleSearchTableHandler.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/AddScheduleSearch/View/AddScheduleSearchListView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/AddScheduleSearch/View/AddScheduleSearchTableViewCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/AddScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ViewController/ScheduleViewController.swift
Labels: feat

#132 feat: Custom Time Picker 제작 및 연결
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/AddScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleCalendar/CalendarManager.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleCalendar/View/ScheduleCalendarCollectionViewCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleCalendar/View/ScheduleCalendarView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleCalendar/ViewController/ScheduleCalendarViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleTimer/ScheduleTimeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleTimer/ScheduleTimeViewController.swift
Labels: feat

#136 fix: 메인 폴더 폴더링 버그 해결
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Models/BrowseItem/BrowseItem.swift
  iOS_Wegg/iOS_Wegg/Models/EmojiModel/EmojiModel.swift
  iOS_Wegg/iOS_Wegg/Models/HotPlaceModel/HotPlaceSectionModel.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Login/LoginRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Login/LoginResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/HotPlaceRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/HotPlacesResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/UploadRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/UploadResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleSearchRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleSearchResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/BaseResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/SignUpRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/SignUpResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/VerificationRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Todo/TodoRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Todo/TodoResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/User/UserModel.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/User/UserOccupation.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/User/UserReason.swift
  iOS_Wegg/iOS_Wegg/Models/PostModel/CommentModel.swift
  iOS_Wegg/iOS_Wegg/Models/PostModel/PostDetailModel.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/CameraSessionManagerDelegate.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Models/Todo/TodoRequest.swift
  iOS_Wegg/iOS_Wegg/Models/Todo/TodoResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/NetworkModel/Todo/TodoRequest.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/NetworkModel/Todo/TodoResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Models/ResponseModel/SignUp/SignUpResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
Labels: bug

#138 feat: 지각 토글 여부에 따른 지각 버튼 활성화
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/AddScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/ScheduleDetailSettingView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
Labels: feat, refactor

#140 feat: 일정 추가 API 연결
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Schedule/ScheduleAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Add/AddScheduleRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Add/AddScheduleResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleModels.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Search/ScheduleSearchRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Search/ScheduleSearchResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/AddScheduleSearch/AddScheduleSearchTableHandler.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/AddScheduleView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/View/ScheduleDetailSettingView.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleCalendar/CalendarManager.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleCalendar/ViewController/ScheduleCalendarViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/DatePicker/ScheduleTimer/ScheduleTimeViewController.swift
Labels: feat

#144 feat: 일정 삭제 및 스위치 토글 API 연결
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Schedule/ScheduleAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIView+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Delete/DeleteScheduleResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/OnOff/OnOffScheduleRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/OnOff/OnOffScheduleResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleModels.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/View/ScheduleCardCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ViewController/ScheduleViewController.swift
Labels: feat

#146 feat: 설정 화면 구현 및 프로필 수정
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Component/Button/Settings/SettingBackButton.swift
  iOS_Wegg/iOS_Wegg/Component/Button/Settings/SettingRefreshButton.swift
  iOS_Wegg/iOS_Wegg/Component/Button/Settings/SettingViewButton.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Auth/LoginManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Notifications/SSEClient.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Settings/NotificationService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Settings/SettingsAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Settings/SettingsService.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIFont+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Login/LoginResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Settings/ProfileModifyRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Settings/ProfileModifyResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/SignUpResponse.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/Enums/NotificationFrequency.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/Enums/NotificationType.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/Enums/ProfileVisibility.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/SettingsConfiguration.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/SettingsModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Settings/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Settings/refresh.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Settings/refresh.imageset/refresh.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Settings/settings_wegg.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Settings/settings_wegg.imageset/settings_wegg.png
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/LoginViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/MainTabBarController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/SettingBaseCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/SettingDisclosureCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/SettingRadioCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/SettingToggleCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/SettingsStorage.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/ProfileEditViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/SettingBaseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/SettingsViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/ProfileEditView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/SettingsView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/EmailSignUpViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpCompleteViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/EmailSignUpView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/GetAlertPermissionView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/NameInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/NickNameInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/OccupationInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/PhoneNumberInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/PhoneNumberVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/ReasonInputView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/ServiceAgreementView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/SignUpCompleteView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/SignUpView.swift
Labels: bug, feat

#124 Feat: 둘러보기탭 API 호출
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Browse/BrowseAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Browse/BrowseService.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIImageView+extensions.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Browse/BrowseRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Browse/BrowseResponse.swift
  iOS_Wegg/iOS_Wegg/Models/PostModel/PostDetailModel.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/post_placeholder.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/post_placeholder.imageset/post1-1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/profile_placeholder.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Browse/profile_placeholder.imageset/profile1.png
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/Views/PostDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/ViewController/SearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/ViewController/BrowseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/CollectionView/BrowseCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/CollectionView/BrowseSectionHeaderView.swift
Labels: feat

#149 feat: 사용자 검색 UI
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Models/SearchModel/User.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Cell/SearchResultCellTableViewCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/ViewController/SearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchBarView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchResultView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Views/SearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/ViewController/BrowseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseSearchView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Views/BrowseView.swift
Labels: feat

#155 feat: 캘린더 화면 팔로우 라벨 API 연동
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/Follow/FollowLabelAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Follow/FollowLabelResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/CalendarView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/ViewController/CalendarViewController.swift
Labels: feat

#150 feat: SSE 알림 기능 구현.
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Notifications/SSEClient.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/GetAlertPermissionViewController.swift
Labels: feat

#154 feat: 장소 상세 정보 API 연결 및 UI 업데이트
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/HotPlacesAPI.swift
  iOS_Wegg/iOS_Wegg/Models/HotPlaceModel/HotPlaceSectionModel.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/DetailInfo/HotplaceDetailInfoRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/DetailInfo/HotplaceDetailInfoResponse.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/View/Table/MapSearchTableHandler.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/ViewController/MapSearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/CollectionView/Cell/PlaceDetailImageCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/PlaceDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailCollectionHandler.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailViewController.swift
Labels: feat

#156 feat: 홈 주간 화면 렌더링 API 연동 (사진URL 달걀모양 수정 필요)
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/WeeklyRender/WeeklyRenderAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/WeeklyRender/WeeklyRenderResponse.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/brokenEgg.imageset/1brokenEgg.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/brokenEgg.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/brokenEgg.imageset/brokenEgg.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/emptyEgg.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/emptyEgg.imageset/emptyEgg.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Home/emptyEgg.imageset/emptyEgg1.png
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/AuthView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/EggProgressView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/HomeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/SwipeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/ToDoListview.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/WeeklyEggView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
Labels: feat

#158 feat: 장소 인증 API 연결
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/PlaceVerificationAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/PlaceVerification/CheckPlaceVerificationRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/PlaceVerification/CheckPlaceVerificationResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/PlaceVerification/FetchPlaceVerificationResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleModels.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationInfoView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationViewController.swift
Labels: feat

#160 feat: 장소 인증 화면 네비게이션 이동
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/WeeklyRender/WeeklyRenderAPI.swift
  iOS_Wegg/iOS_Wegg/Models/HotPlaceModel/HotPlaceSectionModel.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/WeeklyRender/WeeklyRenderResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/All/HotPlacesResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/DetailInfo/HotplaceDetailInfoResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/All/FetchAllSchedulesResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleModels.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/place_back_button.imageset/Frame 427319003.png
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/View/AuthView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/HomeMain/ViewController/HomeViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/Header/HotPlaceCellHeader.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/MapOverlayView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/ViewController/MapSearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/View/ScheduleCardCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ViewController/ScheduleViewController.swift
Labels: feat, refactor

#161 feat: 캘린더 화면 공부 달력 및 공부 시간 달력 API 연동
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/Calendar/MonthlyRenderAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Calendar/MonthlyRenderResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/CalendarCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/CalendarView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/StudyTimeCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/StudyTimeView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/View/ToggleButtonView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Calendar/ViewController/CalendarViewController.swift
Labels: feat

#164 feat: 알림 목록 가져오기 API 연동
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/Notification/NotificationAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/GetNotiResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/FollowCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/NotiCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/View/NotiFollowView.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/ViewController/FollowViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/ViewController/NotiViewController.swift
Labels: feat

#165 feat: 연락처 추가 로직 구현
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Component/SignUp/TimerManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Login/Storage/UserSignUpStorage.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Auth/AuthService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Follow/FollowInfoAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Follow/FollowService.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/Follow/FollowLabelAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Follow/FollowRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Follow/FollowResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/BaseResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/SignUpRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/SignUp/SignUpResponse.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/SignUp/weggy.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/SignUp/weggy.imageset/weggy.png
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/Login/View/PasswordResetVerificationView.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/PasswordResetVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Cells/ContactFriendCell.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/ContactPermissionViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/GetAlertPermissionViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/NickNameInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpCompleteViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/SignUpViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/ContactPermissionView.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/Views/PhoneNumberVerificationView.swift
Labels: bug, feat, refactor

#167 feat: 게시물 댓글과 이모지 API 연동
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Post/PostDetailAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Post/PostDetailService.swift
  iOS_Wegg/iOS_Wegg/Models/BrowseItem/BrowseItem.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/Comment/CommentRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/Comment/CommentResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/Emoji/EmojiRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Post/Emoji/EmojiResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleModels.swift
  iOS_Wegg/iOS_Wegg/Models/PostModel/CommentModel.swift
  iOS_Wegg/iOS_Wegg/Models/PostModel/PostDetailModel.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/ViewController/CommentViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/ViewController/PostDetailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/Views/Cell/CommentCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/Views/CommentView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/Views/PlusEmojiView.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/PostDetail/Views/PostDetailView.swift
Labels: feat

#170 feat: 알림 읽기 API 연동
  iOS_Wegg/iOS_Wegg/Core/Services/API/APIConstants.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Home/Notification/NotificationAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Home/Notification/ViewController/NotiViewController.swift
Labels: feat

#171 feat: 사용자 검색 API 연동
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/User/UserAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/User/UserService.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Search/UserSearchResponse.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/Cell/SearchResultCellTableViewCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Browse/Search/ViewController/SearchViewController.swift
Labels: feat

#172 feat: 모든 API 연결(일정 수정 제외)
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/NaverMapManager.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Map/HotPlacesAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Schedule/ScheduleAPI.swift
  iOS_Wegg/iOS_Wegg/Models/HotPlaceModel/HotPlaceSectionModel.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/All/HotPlaceRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/PlaceSave/DeletePlaceResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/PlaceSave/FetchAllSavePlaceRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/PlaceSave/FetchAllSavePlaceResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Map/PlaceSave/SavePlaceResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/PlaceVerification/CheckPlaceVerificationResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Edit/EditScheduleStatusRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Edit/EditScheduleStatusResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/ScheduleModels.swift
  iOS_Wegg/iOS_Wegg/Models/Protocol/MapManagerProtocol.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/reload_icon.imageset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/reload_icon.imageset/Frame 427319023.png
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/Map/Delegate/Delegate.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/CollectionView/CollectionLayout/HotPlaceCollectionLayout.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/HotPlaceSheetView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/View/MapOverlayView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/HotPlaceSheetViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/View/PlaceDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceDetail/ViewController/PlaceDetailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/PlaceVerification/PlaceVerificationViewController.swift
Labels: bug, feat

#173 feat: 설정 구현 완료
  iOS_Wegg/iOS_Wegg/Component/Button/Settings/SettingBackButton.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Settings/SettingsAPI.swift
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Settings/SettingsService.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Settings/ProfileModifyResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Settings/SettingsUpdateRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Settings/SettingsUpdateResponse.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/Enums/NotificationType.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/Enums/ProfileVisibility.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/FeatureSettings.swift
  iOS_Wegg/iOS_Wegg/Models/SettingsModel/SettingsConfiguration.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/PointProduct.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/SettingDisclosureCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Cells/SettingToggleCell.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/SettingsStorage.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/Feature/EggBreakSettingViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/Feature/FeatureSettingViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/Notification/NotificationDetailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/Notification/NotificationSettingViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/PointPurchaseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/Privacy/PrivacySettingViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/ProfileEditViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/ViewControllers/SettingsViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/Feature/EggBreakSettingView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/Feature/FeatureSettingView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/Notification/NotificationDetailView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/Notification/NotificationSettingView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/PointPurchaseView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/Privacy/PrivacySettingView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/ProfileEditView.swift
  iOS_Wegg/iOS_Wegg/Screen/Settings/Views/SettingsView.swift
Labels: feat

#174 feat: 주석 제거
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberVerificationViewController.swift
Labels: feat

#175 feat: 키보드 내려가는 로직 추가
  iOS_Wegg/iOS_Wegg/App/SceneDelegate.swift
  iOS_Wegg/iOS_Wegg/Core/Utilities/Extensions/UIViewController+extension.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadResponse.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/Images/Map/reload_icon.imageset/Contents 2.json
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/EmailLoginViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/PasswordResetEmailViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Login/ViewController/PasswordResetVerificationViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/EmailSignUpViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/NameInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/NickNameInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/OccupationInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberInputViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/SignUp/ViewControllers/PhoneNumberVerificationViewController.swift
Labels: feat

#179 feat: 앱 이름 및 로고 적용
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadResponse.swift
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/AppIcon.appiconset/weggIcon 1.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/AppIcon.appiconset/weggIcon 2.png
  iOS_Wegg/iOS_Wegg/Resources/Assets.xcassets/AppIcon.appiconset/weggIcon.png
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
Labels: Style, chore

#180 feat:edit schedule api
  iOS_Wegg/iOS_Wegg.xcodeproj/project.pbxproj
  iOS_Wegg/iOS_Wegg/Core/Services/API/Targets/Schedule/ScheduleAPI.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Home/Notification/MarkAsReadResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Edit/EditScheduleRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Edit/EditScheduleResponse.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Edit/Status/EditScheduleStatusRequest.swift
  iOS_Wegg/iOS_Wegg/Models/NetworkModel/Schedule/Edit/Status/EditScheduleStatusResponse.swift
  iOS_Wegg/iOS_Wegg/Resources/Info.plist
  iOS_Wegg/iOS_Wegg/Screen/Browse/ViewController/BrowseViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/HotPlace/ViewController/MapViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Map/MapSearch/ViewController/MapSearchViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/AddSchedule/ViewController/AddScheduleViewController.swift
  iOS_Wegg/iOS_Wegg/Screen/Schedule/ViewController/ScheduleViewController.swift
Labels: feat
